- name: copy mongodb yum repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
  when: schema_load

- name: Install mongodb server
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
  when: schema_load

- name: load schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.nvrnagella.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
  when: schema_load